name: Android CI

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew     
    - name: Build APK
      run: bash ./gradlew assembleRelease --stacktrace
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
         name: app-release.apk
         path: app/build/outputs/apk/release/app-release.apk
